# This repository is built using VSTS.

variables:
  buildConfiguration: 'Release'

steps:
  - task: DotNetCoreInstaller@0
    inputs:
      version: '2.1.302'

  - task: DotNetCoreCLI@2
    inputs:
      command: 'restore'
      projects: '**/*.csproj'

  - task: DotNetCoreCLI@2
    inputs:
      command: 'build'
      projects: '**/*.csproj'
      arguments: '--configuration $(buildConfiguration)'

#  - task: DotNetCoreCLI@2
#    inputs:
#      command: 'test'
#      projects: '**/*[Tt]ests/*.csproj'
#      arguments: '--configuration $(buildConfiguration)'

  - task: DotNetCoreCLI@2
    inputs:
      command: 'publish'
      arguments: '--configuration $(buildConfiguration) --output $(build.artifactStagingDirectory)'

  - task: PublishBuildArtifacts@1