# This repository is built using VSTS.

variables:
  buildConfiguration: 'Release'

steps:
  - task: DotNetCoreInstaller@0
    inputs:
      version: '2.1.302'
    displayName: Install DotNetCoreCLI

  - task: DotNetCoreCLI@2
    inputs:
      command: 'restore'
      projects: '**/*.csproj'
    displayName: Restore packages

  - task: DotNetCoreCLI@2
    inputs:
      command: 'build'
      projects: '**/*.csproj'
      arguments: '--configuration $(buildConfiguration)'
    displayName: Build all packages

#  - task: DotNetCoreCLI@2
#    inputs:
#      command: 'test'
#      projects: '**/*[Tt]ests/*.csproj'
#      arguments: '--configuration $(buildConfiguration)'
#    displayName: Run all tests

  - task: DotNetCoreCLI@2
    inputs:
      command: 'publish'
      arguments: '--configuration $(buildConfiguration) --output $(build.artifactStagingDirectory)'
    displayName: Publish solution

  - task: PublishBuildArtifacts@1
    displayName: Publish Build Artifacts